FROM nagadomi/torch7:cuda10.1-cudnn7-devel-ubuntu18.04

# move from context to /workspace
COPY . /workspace

RUN apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/3bf863cc.pub && \
    git config --global url."https://".insteadOf git:// && \
    apt-get update &&  \
    apt-get install -y \
        build-essential \
        python-dev \
        python-pip \
        python3-pip \
        wget \
        curl \
        git \
        software-properties-common


RUN pip install -r /workspace/artifact/setup/requirements.txt &&  \
    python -c "import nltk; nltk.download('punkt')" && \
    wget -q -P /workspace/data/embed 'https://github.com/RaRe-Technologies/gensim-data/releases/download/word2vec-google-news-300/word2vec-google-news-300.gz' && \
    gunzip /workspace/data/embed/word2vec-google-news-300.gz && \
    mkdir -p /workspace/embed && \
    pip3 install sacrebleu==2.1.0 pandas seaborn numpy && \
    luarocks install tds && \
    luarocks install lua-zlib

WORKDIR /workspace


