FROM ubuntu:14.04

ENV PYTHON_VERSION 2.7.18
ENV PYENV_GIT_TAG=v2.2.5

RUN apt-get update && \
    apt-get install -y make build-essential libssl-dev \
    zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev \
    wget curl llvm libncursesw5-dev xz-utils tk-dev \
    libxml2-dev libxmlsec1-dev libffi-dev liblzma-dev curl \
    git software-properties-common

ENV PYENV_ROOT /root/.pyenv
ENV PATH $PYENV_ROOT/shims:$PYENV_ROOT/bin:$PATH

RUN export PYENV_GIT_TAG=v2.2.5 && \
    curl https://pyenv.run | bash && \
#    pyenv update && \
    pyenv install $PYTHON_VERSION && \
    pyenv global $PYTHON_VERSION && \
    pyenv rehash



#RUN apt-get update && apt-get install -y \
#    build-essential \
#    python-dev \
#    python-pip \
#    wget \
#    curl \
#    git \
#    software-properties-common

RUN git config --global url."https://".insteadOf git://

RUN curl -s https://raw.githubusercontent.com/torch/ezinstall/master/install-deps | bash -e
RUN git clone https://github.com/torch/distro.git ~/torch --recursive
RUN cd ~/torch && ./install.sh && \
    cd install/bin && \
    ./luarocks install nn && \
    ./luarocks install tds

RUN apt-get install -y uuid-dev

RUN cd ~ && wget https://github.com/zeromq/zeromq2-x/releases/download/v2.1.11/zeromq-2.1.11.tar.gz && \
    tar -xvf zeromq-2.1.11.tar.gz && cd zeromq-2.1.11 && \
    ./configure && make && \ 
    make install && sudo ldconfig
    

RUN cd ~/torch/install/bin && ./luarocks install lua-zmq ZEROMQ_LIBDIR=/usr/local/lib ZEROMQ_INCDIR=/usr/local/include

RUN cd ~/torch/install/bin ./luarocks install restserver-xavante
RUN cd ~/torch/install/bin ./luarocks install dkjson
RUN cd ~/torch/install/bin ./luarocks install lua-zlib

#RUN cd ~ && \
#    git clone --recursive https://github.com/senisioi/NeuralTextSimplification.git && \
#    cd ./NeuralTextSimplification && \
#    pip install -r src/requirements.txt && \
#    python src/download_models.py ./models

COPY artifact/setup/requirements.txt /opt/app/requirements.txt
RUN pip install -r /opt/app/requirements.txt

#RUN pip install -r requirements.txt
# Packages that require runtime download can be cached by running the python -c "CODE"
# Replace "CODE" with the lines that handle downloading
# RUN python -c "CODE"
# git clone --branch 0.13.1 https://github.com/RaRe-Technologies/gensim.git
# pip install git+git@github.com:RaRe-Technologies/gensim.git@d4f9cc506a3e769c1496b26b9e673d41d8db1b6c
WORKDIR /workspace

EXPOSE 5556
